Repository venzym/devcourse_algorithm, pull requests merged in 2022-01, with the labels that each got.

#9 빗물 - 이범진
  src/january/first/가르침/Venzym.java
  src/january/first/빗물/Venzym.java
Labels: simulation

#17 부분합 - 이범진
  src/january/first/부분합/Venzym.java
Labels: two-pointer

#10 빗물 - 유지훈
  src/january/first/빗물/Youji2.java
Labels: simulation

#8 빗물 - 유현호
  src/january/first/가르침/YHH.java
  src/january/first/빗물/YHH.java
Labels: simulation

#11 빗물- 박연수
  src/january/first/빗물/Yeonsoo.py
Labels: simulation

#29 전투 - 박연수
  src/january/first/멀티탭스케줄링/Yeonsoo.py
  src/january/second/숨바꼭질2/숨바꼭질-박연수.py
  src/january/second/전투/전투.py
Labels: bfs/dfs
